version: '3.8'

services:
  app:
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-ai
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: answerai
      POSTGRES_PASSWORD: answerai
      POSTGRES_DB: answerai

volumes:
  postgres-data: